---
name: Build PDF Release
on:
  push:
    branches:
      - main
jobs:
  Build:
    if: github.repository == 'jmunixusers/presentations'
    name: Build PDF release bundle
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install chromium-browser
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: "${{ runner.os }}-node-"
          restore-keys: |
            "${{ runner.os }}-node-"
      - name: Install marp
        run: |
          npm install --save-dev @marp-team/marp-cli markdown-pdf
      - name: Build PDFs
        run: |
          for input in *.md */*.md; do
            output="${input%.md}.pdf"
            echo "Input: $input, output $output"
            if [[ "$(grep -l 'marp: true' "$input")" ]]; then
              npx marp --allow-local-files "$input" -o "$output"
            else
              npx markdown-pdf "$input" -o "$output"
            fi
            zip -g PDF.zip "$output"
          done
      - name: Set GitHub auth token
        run: |
          gh config set -h github.com oauth_token "${{ secrets.GITHUB_TOKEN }}"
      - name: Create updated release
        run: |
          gh release delete presentation-latest -y || true
          git push --delete origin presentation-latest || true
          gh release create presentation-latest PDF.zip
